export const fourniture = [
  { name: "Canapé", value: "Canapés" },
  { name: "Table à manger", value: "Tables à manger" },
  { name: "Chaise", value: "Chaises" },
  { name: "Armoire", value: "Armoires" },
  { name: "Lit double", value: "Lits doubles" },
  { name: "Bureau", value: "Bureaux" },
  { name: "Étagère", value: "Étagères" },
  { name: "Buffet", value: "Buffets" },
  { name: "Commode", value: "Commodes" },
  { name: "Meuble TV", value: "Meubles TV" },
  { name: "Fauteuil", value: "Fauteuils" },
  { name: "Console", value: "Consoles" },
  { name: "Vitrine", value: "Vitrines" },
  { name: "Bibliothèque", value: "Bibliothèques" },
  { name: "Coffre", value: "Coffres" },
  { name: "Table basse", value: "Tables basses" },
  { name: "Table d'appoint", value: "Tables d'appoint" },
  { name: "Lit simple", value: "Lits simples" },
  { name: "Lit superposé", value: "Lits superposés" },
  { name: "Canapé-lit", value: "Canapés-lits" },
  { name: "Tabouret", value: "Tabourets" },
  { name: "Pouf", value: "Poufs" },
  { name: "Banc", value: "Bancs" },
  { name: "Coiffeuse", value: "Coiffeuses" },
  { name: "Miroir", value: "Miroirs" },
  { name: "Lampadaire", value: "Lampadaires" },
  { name: "Applique murale", value: "Appliques murales" },
  { name: "Suspension", value: "Suspensions" },
  { name: "Tapis", value: "Tapis" },
  { name: "Matelas", value: "Matelas" },
  { name: "Commode à langer", value: "Tables à langer" },
  { name: "Meuble à chaussures", value: "Meubles à chaussures" },
  { name: "Porte-manteau", value: "Porte-manteaux" },
  { name: "Guéridon", value: "Guéridons" },
  { name: "Paravent", value: "Paravents" },
  { name: "Chiffonnier", value: "Chiffonniers" },
  { name: "Escabeau", value: "Escabeaux" },
  { name: "Cintre", value: "Cintres" },
  { name: "Porte-revues", value: "Porte-revues" },
  { name: "Bougeoir", value: "Bougeoirs" },
  { name: "Cendrier", value: "Cendriers" },
  { name: "Buste de couture", value: "Bustes de couture" },
  { name: "Penderie", value: "Penderies" },
  { name: "Porte-parapluie", value: "Porte-parapluies" },
  { name: "Garde-robe", value: "Garde-robes" },
  { name: "Chevet", value: "Chevets" },
  { name: "Desserte", value: "Dessertes" },
  { name: "Chariot de bar", value: "Chariots de bar" },
  { name: "Lit à baldaquin", value: "Lits à baldaquin" },
  { name: "Méridienne", value: "Méridiennes" },
  { name: "Chaise pliante", value: "Chaises pliantes" },
  { name: "Tabouret de bar", value: "Tabourets de bar" },
  { name: "Porte-bouteilles", value: "Porte-bouteilles" },
  { name: "Cheminée décorative", value: "Cheminées décoratives" },
  { name: "Chandelier", value: "Chandeliers" },
  { name: "Armoire à vin", value: "Armoires à vin" },
  { name: "Table de chevet", value: "Tables de chevet" },
  { name: "Parure de lit", value: "Parures de lit" },
  { name: "Table de billard", value: "Tables de billard" },
  { name: "Bibliothèque d'angle", value: "Bibliothèques d'angle" },
  { name: "Meuble à CD/DVD", value: "Meubles à CD/DVD" },
  { name: "Chaise de bureau", value: "Chaises de bureau" },
  { name: "Étagère murale", value: "Étagères murales" },
  { name: "Console d'entrée", value: "Consoles d'entrée" },
  { name: "Porte-manteau mural", value: "Porte-manteaux muraux" },
  {
    name: "Tabouret de bar réglable en hauteur",
    value: "Tabourets de bar réglables en hauteur",
  },
  { name: "Pouf de rangement", value: "Poufs de rangement" },
  { name: "Table pliante", value: "Tables pliantes" },
  { name: "Banc de rangement", value: "Bancs de rangement" },
  { name: "Table de jardin", value: "Tables de jardin" },
  { name: "Chaise longue inclinable", value: "Chaises longues inclinables" },
  { name: "Bureau d'angle", value: "Bureaux d'angle" },
  { name: "Caisson de bureau", value: "Caisses de bureau" },
  { name: "Chaise de salle à manger", value: "Chaises de salle à manger" },
  { name: "Lampe de bureau", value: "Lampes de bureau" },
  { name: "Table de réunion", value: "Tables de réunion" },
  { name: "Armoire de cuisine", value: "Armoires de cuisine" },
  { name: "Lit gigogne", value: "Lits gigognes" },
  { name: "Canapé d'angle", value: "Canapés d'angle" },
  { name: "Bibliothèque en échelle", value: "Bibliothèques en échelle" },
  { name: "Table de jeu", value: "Tables de jeu" },
  {
    name: "Meuble à chaussures avec miroir",
    value: "Meubles à chaussures avec miroir",
  },
  { name: "Chaise de bar en cuir", value: "Chaises de bar en cuir" },
  {
    name: "Chaise de bureau ergonomique",
    value: "Chaises de bureau ergonomiques",
  },
  { name: "Étagère d'angle", value: "Étagères d'angle" },
  { name: "Cuisine équipée", value: "Cuisines équipées" },
  { name: "Table de cuisine", value: "Tables de cuisine" },
  { name: "Chaise de cuisine", value: "Chaises de cuisine" },
  { name: "Tabouret de bar de cuisine", value: "Tabourets de bar de cuisine" },
  { name: "Buffet de cuisine", value: "Buffets de cuisine" },
  {
    name: "Meuble de rangement pour cuisine",
    value: "Meubles de rangement pour cuisine",
  },
  { name: "Îlot de cuisine", value: "Îlots de cuisine" },
  { name: "Étagère murale de cuisine", value: "Étagères murales de cuisine" },
  { name: "Meuble d'angle de cuisine", value: "Meubles d'angle de cuisine" },
  { name: "Porte-ustensiles de cuisine", value: "Porte-ustensiles de cuisine" },
  { name: "Poubelle de cuisine", value: "Poubelles de cuisine" },
  {
    name: "Poubelle de tri sélectif de cuisine",
    value: "Poubelles de tri sélectif de cuisine",
  },
  { name: "Range-bouteilles de cuisine", value: "Range-bouteilles de cuisine" },
  { name: "Range-épices de cuisine", value: "Range-épices de cuisine" },
  { name: "Range-couverts de cuisine", value: "Range-couverts de cuisine" },
  { name: "Range-tasses de cuisine", value: "Range-tasses de cuisine" },
  { name: "Range-assiettes de cuisine", value: "Range-assiettes de cuisine" },
  { name: "Range-casseroles de cuisine", value: "Range-casseroles de cuisine" },
  { name: "Range-poêles de cuisine", value: "Range-poêles de cuisine" },
  { name: "Range-plats de cuisine", value: "Range-plats de cuisine" },
  { name: "Range-serviettes de cuisine", value: "Range-serviettes de cuisine" },
  { name: "Porte-rouleau de cuisine", value: "Porte-rouleaux de cuisine" },
  {
    name: "Distributeur de papier de cuisine",
    value: "Distributeurs de papier de cuisine",
  },
  { name: "Placard de cuisine", value: "Placards de cuisine" },
  { name: "Tiroir de cuisine", value: "Tiroirs de cuisine" },
  { name: "Crédence de cuisine", value: "Crédences de cuisine" },
  { name: "Plan de travail de cuisine", value: "Plans de travail de cuisine" },
  { name: "Hotte aspirante de cuisine", value: "Hottes aspirantes de cuisine" },
  { name: "Évier de cuisine", value: "Éviers de cuisine" },
  { name: "Robinet de cuisine", value: "Robinets de cuisine" },
  {
    name: "Poubelle automatique de cuisine",
    value: "Poubelles automatiques de cuisine",
  },
  { name: "Balance de cuisine", value: "Balances de cuisine" },
  { name: "Mixeur de cuisine", value: "Mixeurs de cuisine" },
  { name: "Batteur de cuisine", value: "Batteurs de cuisine" },
  { name: "Robot de cuisine", value: "Robots de cuisine" },
  { name: "Couteau de cuisine", value: "Couteaux de cuisine" },
  {
    name: "Planche à découper de cuisine",
    value: "Planches à découper de cuisine",
  },
  {
    name: "Essoreuse à salade de cuisine",
    value: "Essoreuses à salade de cuisine",
  },
  { name: "Râpe de cuisine", value: "Râpes de cuisine" },
  { name: "Éplucheur de cuisine", value: "Éplucheurs de cuisine" },
  { name: "Louche de cuisine", value: "Louches de cuisine" },
  { name: "Cuillère de cuisine", value: "Cuillères de cuisine" },
  { name: "Four de cuisine", value: "Fours de cuisine" },
  { name: "Micro-ondes de cuisine", value: "Micro-ondes de cuisine" },
  { name: "Cuisinière de cuisine", value: "Cuisinières de cuisine" },
  { name: "Réfrigérateur de cuisine", value: "Réfrigérateurs de cuisine" },
  { name: "Congélateur de cuisine", value: "Congélateurs de cuisine" },
  { name: "Lave-vaisselle de cuisine", value: "Lave-vaisselles de cuisine" },
  { name: "Machine à café de cuisine", value: "Machines à café de cuisine" },
  { name: "Bouilloire de cuisine", value: "Bouilloires de cuisine" },
  { name: "Grille-pain de cuisine", value: "Grille-pains de cuisine" },
  { name: "Presse-agrumes de cuisine", value: "Presse-agrumes de cuisine" },
  { name: "Moulin à poivre de cuisine", value: "Moulins à poivre de cuisine" },
  { name: "Moulin à sel de cuisine", value: "Moulins à sel de cuisine" },
  { name: "Théière de cuisine", value: "Théières de cuisine" },
  { name: "Tire-bouchon de cuisine", value: "Tire-bouchons de cuisine" },
  { name: "Verres de cuisine", value: "Verres de cuisine" },
  { name: "Tasses de cuisine", value: "Tasses de cuisine" },
  { name: "Assiettes de cuisine", value: "Assiettes de cuisine" },
  { name: "Couverts de cuisine", value: "Couverts de cuisine" },
  { name: "Plats de cuisine", value: "Plats de cuisine" },
  { name: "Saladiers de cuisine", value: "Saladiers de cuisine" },
  {
    name: "Boîtes de conservation de cuisine",
    value: "Boîtes de conservation de cuisine",
  },
  { name: "Moules de cuisine", value: "Moules de cuisine" },
  { name: "Spatules de cuisine", value: "Spatules de cuisine" },
  { name: "Fouets de cuisine", value: "Fouets de cuisine" },
  {
    name: "Salières et poivrières de cuisine",
    value: "Salières et poivrières de cuisine",
  },
  { name: "Décapsuleurs de cuisine", value: "Décapsuleurs de cuisine" },
  { name: "Ciseaux de cuisine", value: "Ciseaux de cuisine" },
  { name: "Pelles de cuisine", value: "Pelles de cuisine" },
  {
    name: "Louche à spaghetti de cuisine",
    value: "Louches à spaghetti de cuisine",
  },
  { name: "Écumoire de cuisine", value: "Écumoires de cuisine" },
  { name: "Entonnoir de cuisine", value: "Entonnoirs de cuisine" },
  { name: "Passoire de cuisine", value: "Passoires de cuisine" },
  { name: "Bol de cuisine", value: "Bols de cuisine" },
  { name: "Pichet de cuisine", value: "Pichets de cuisine" },
  { name: "Plateaux de cuisine", value: "Plateaux de cuisine" },
  { name: "Carafe de cuisine", value: "Carafe de cuisine" },
  { name: "Bouteilles de cuisine", value: "Bouteilles de cuisine" },
];
